### ISSUE TITLE
Remover automaticamente caronas após a hora

### ISSUE THREAD

**Issue by ktalmeida** [henriquemaio/CaronasBot#2]
Fala pessoal, acho que seria uma boa ideia removermos do banco as caronas para os horários que já passaram para aquele dia e possivelmente adicionar para o dia seguinte se o horário da carona for antes do horário atual. O que acham? Eu posso implementar isso, mas precisaria mudar o banco, seria problema? Obrigado!

**Comment by henriquemaio** [comment]
Olá Kayan, 

Primeiramente gostaria de agradecer imensamente sua colaboração e esforço em melhorar o bot e aproveito para convidá-lo para nosso grupo no Telegram onde podemos discutir mais diretamente, entra lá: https://t.me/joinchat/AAAAAD2R2WM8snmaxACnYQ

Quanto a sua sugestão, atualmente o bot remove as caronas automaticamente após 24h (implementação do Victor Bustamante).
O motivo de não remover após ultrapassado o horário da carona é que por ter gente que pega ou oferece carona em horários distintos, fica um pouco complicado saber se ela ofereceu para o dia atual ou para o dia seguinte.

Por exemplo:

São 15h da tarde e um usuário escreve:
/ida 17

Ele pode ser um estudante que estuda no período noturno e está oferecendo sua carona para daqui a 2 horas ou pode ser algum apressadinho que está oferecendo para as 17h do dia seguinte. 

Quanto à mudança no banco, não vejo problemas nisso. Sendo mudanças que melhorem ainda mais o Bot e mantenham ele retrocompatível e simples de utilizar, ficaremos felizes.

Um grande abraço!
